name: pos_printer
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  blue_thermal_printer:
    path: blue_thermal_printer
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
